spring:
    datasource:
        url: jdbc:mysql://hasdsd.cn:3307/comp?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            max-lifetime=120000:
